const initialAnimals = ['panda', 'bear', 'cat', 'dog', 'elephant', 'frog'];
const initialColors = [
    'amber',
    'apricot ', 
    'aqua',
    'azure',
    'beige',
    'black',
    'blue',
    'bronze',
    'brown', 
    'burgundy',
    'cyan',
    'gold',
    'gray',
    'green', 
    'indigo',
    'ivory',
    'jade',
    'lavender',
    'lemon',
    'lilac',
    'lime', 
    'magenta', 
    'maroon',
    'mint',
    'navy',
    'ochre', 
    'olive',
    'orange',
    'orchid', 
    'peach',
    'pink',
    'plum',
    'puce',
    'purple',  
    'red', 
    'rose',
    'ruby', 
    'russet', 
    'salmon', 
    'sangria',
    'sapphire',
    'scarlet',
    'silver',
    'teal', 
    'tomato',
    'turquoise',
    'vermilion',
    'violet', 
    'wheat', 
    'white',
    'yellow'
  ];

export { initialColors, initialAnimals };